// This code was generated by Hypar.
// Edits to this code will be overwritten the next time you run 'hypar init'.
// DO NOT EDIT THIS FILE.

using Elements;
using Elements.GeoJSON;
using Elements.Geometry;
using Elements.Geometry.Solids;
using Elements.Validators;
using Elements.Serialization.JSON;
using Hypar.Functions;
using Hypar.Functions.Execution;
using Hypar.Functions.Execution.AWS;
using Hypar.Model;
using System;
using System.Collections.Generic;
using System.Linq;
using Line = Elements.Geometry.Line;
using Polygon = Elements.Geometry.Polygon;

namespace Searchable
{
    #pragma warning disable // Disable all warnings

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "10.1.21.0 (Newtonsoft.Json v13.0.0.0)")]
    
    public  class SearchableInputs : ArgsBase
    
    {
        [Newtonsoft.Json.JsonConstructor]
        
        public SearchableInputs(int @levelCount, string @levelNames, string @searchableLevelNames, SearchableInputsChoices @choices, SearchableInputsSearchableChoices @searchableChoices, Dictionary<string, string> modelInputKeys, string gltfKey, string elementsKey, string ifcKey):
        base(modelInputKeys, gltfKey, elementsKey, ifcKey)
        {
            var validator = Validator.Instance.GetFirstValidatorForType<SearchableInputs>();
            if(validator != null)
            {
                validator.PreConstruct(new object[]{ @levelCount, @levelNames, @searchableLevelNames, @choices, @searchableChoices});
            }
        
            this.LevelCount = @levelCount;
            this.LevelNames = @levelNames;
            this.SearchableLevelNames = @searchableLevelNames;
            this.Choices = @choices;
            this.SearchableChoices = @searchableChoices;
        
            if(validator != null)
            {
                validator.PostConstruct(this);
            }
        }
    
        [Newtonsoft.Json.JsonProperty("Level count", Required = Newtonsoft.Json.Required.DisallowNull, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        [System.ComponentModel.DataAnnotations.Range(5, 1000)]
        public int LevelCount { get; set; }
    
        [Newtonsoft.Json.JsonProperty("Level Names", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public string LevelNames { get; set; }
    
        [Newtonsoft.Json.JsonProperty("Searchable Level Names", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public string SearchableLevelNames { get; set; }
    
        [Newtonsoft.Json.JsonProperty("Choices", Required = Newtonsoft.Json.Required.DisallowNull, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        [Newtonsoft.Json.JsonConverter(typeof(Newtonsoft.Json.Converters.StringEnumConverter))]
        public SearchableInputsChoices Choices { get; set; }
    
        [Newtonsoft.Json.JsonProperty("Searchable Choices", Required = Newtonsoft.Json.Required.DisallowNull, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        [Newtonsoft.Json.JsonConverter(typeof(Newtonsoft.Json.Converters.StringEnumConverter))]
        public SearchableInputsSearchableChoices SearchableChoices { get; set; }
    
    }
    
    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "10.1.21.0 (Newtonsoft.Json v13.0.0.0)")]
    public enum SearchableInputsChoices
    {
        [System.Runtime.Serialization.EnumMember(Value = @"First option")]
        First_option = 0,
    
        [System.Runtime.Serialization.EnumMember(Value = @"Second option")]
        Second_option = 1,
    
        [System.Runtime.Serialization.EnumMember(Value = @"Third option")]
        Third_option = 2,
    
    }
    
    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "10.1.21.0 (Newtonsoft.Json v13.0.0.0)")]
    public enum SearchableInputsSearchableChoices
    {
        [System.Runtime.Serialization.EnumMember(Value = @"First option")]
        First_option = 0,
    
        [System.Runtime.Serialization.EnumMember(Value = @"Second option")]
        Second_option = 1,
    
        [System.Runtime.Serialization.EnumMember(Value = @"Third option")]
        Third_option = 2,
    
    }
}